export interface Quote {
  text: string
  author: string
}

export const REFLECTION_QUOTES: Quote[] = [
  { text: 'With faith, discipline and selfless devotion to duty, there is nothing worthwhile that you cannot achieve.', author: 'Quaid-e-Azam Muhammad Ali Jinnah' },
  { text: 'Think a hundred times before you take a decision, but once that decision is taken, stand by it as one man.', author: 'Quaid-e-Azam Muhammad Ali Jinnah' },
  { text: 'I do not believe in taking the right decision, I take a decision and make it right.', author: 'Muhammad Ali Jinnah' },
  { text: 'The ultimate aim of the ego is not to see something, but to be something.', author: 'Allama Iqbal' },
  { text: 'Nations are born in the hearts of poets, they prosper and die in the hands of politicians.', author: 'Allama Iqbal' },
  { text: 'People of character are the conscience of their nation.', author: 'Allama Iqbal' },
  { text: 'Do not wait for leaders; do it alone, person to person.', author: 'Mother Teresa' },
  { text: 'Success is the sum of small efforts repeated day in and day out.', author: 'Robert Collier' },
  { text: 'What gets measured gets improved.', author: 'Peter Drucker' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Knowing yourself is the beginning of all wisdom.', author: 'Aristotle' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },
  { text: 'Small disciplines repeated with consistency every day lead to great achievements.', author: 'John C. Maxwell' },
  { text: 'The secret of your future is hidden in your daily routine.', author: 'Mike Murdock' },
  { text: 'You cannot improve what you do not measure.', author: 'Tom DeMarco' },
  { text: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
  { text: 'Great things are done by a series of small things brought together.', author: 'Vincent Van Gogh' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln' },
  { text: 'Failure is only the opportunity to begin again, this time more intelligently.', author: 'Henry Ford' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Will Durant' },
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', author: 'James Clear' },
  { text: 'First we make our habits, then our habits make us.', author: 'John Dryden' },
  { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
  { text: 'Today is your opportunity to build the tomorrow you want.', author: 'Ken Poirot' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'Do not watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
  { text: 'You miss one hundred percent of the shots you do not take.', author: 'Wayne Gretzky' },
  { text: 'A little progress each day adds up to big results.', author: 'Satya Nani' },
  { text: 'Fall seven times and stand up eight.', author: 'Japanese Proverb' },
  { text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin' },
  { text: 'Perseverance is not a long race; it is many short races one after the other.', author: 'Walter Elliot' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'You become what you give your attention to.', author: 'Epictetus' },
  { text: 'An ounce of practice is worth more than tons of preaching.', author: 'Mahatma Gandhi' },
  { text: 'Motivation gets you going, but discipline keeps you growing.', author: 'John C. Maxwell' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'Courage is one step ahead of fear.', author: 'Coleman Young' },
  { text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Productivity is never an accident. It is always the result of commitment to excellence.', author: 'Paul J. Meyer' },
  { text: 'A river cuts through rock not because of its power, but because of its persistence.', author: 'James N. Watkins' },
  { text: 'Success is where preparation and opportunity meet.', author: 'Bobby Unser' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
  { text: 'Keep your face always toward the sunshine and shadows will fall behind you.', author: 'Walt Whitman' },
  { text: 'The best preparation for tomorrow is doing your best today.', author: 'H. Jackson Brown Jr.' },
  { text: 'Growth is growth, no matter how small.', author: 'Unknown' }
]

export const PRODUCTIVE_QUOTES: Quote[] = [
  { text: 'Live each day as if it were your last.', author: 'Steve Jobs' },
  { text: 'Spend your next day with as much passion as if it were your last day.', author: 'Daily Planning Reminder' },
  { text: 'Tomorrow belongs to those who prepare for it today.', author: 'Malcolm X' },
  { text: 'A goal without a plan is just a wish.', author: 'Antoine de Saint-Exupery' },
  { text: 'Either you run the day or the day runs you.', author: 'Jim Rohn' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'By failing to prepare, you are preparing to fail.', author: 'Benjamin Franklin' },
  { text: 'The key is not to prioritize what is on your schedule, but to schedule your priorities.', author: 'Stephen Covey' },
  { text: 'Focus on being productive instead of busy.', author: 'Tim Ferriss' },
  { text: 'If you spend too much time thinking about a thing, you will never get it done.', author: 'Bruce Lee' },
  { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
  { text: 'Do first things first, and second things not at all.', author: 'Peter Drucker' },
  { text: 'You do not have to see the whole staircase, just take the first step.', author: 'Martin Luther King Jr.' },
  { text: 'The successful warrior is the average person, with laser-like focus.', author: 'Bruce Lee' },
  { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau' },
  { text: 'Your future is created by what you do today, not tomorrow.', author: 'Robert Kiyosaki' },
  { text: 'Do not count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'I hated every minute of training, but I said: do not quit. Suffer now and live the rest of your life as a champion.', author: 'Muhammad Ali' },
  { text: 'The fight is won or lost far away from witnesses - behind the lines, in the gym, and out there on the road.', author: 'Muhammad Ali' },
  { text: 'It is not enough to be busy; so are the ants. The question is: what are we busy about?', author: 'Henry David Thoreau' },
  { text: 'Never leave that till tomorrow which you can do today.', author: 'Benjamin Franklin' },
  { text: 'Amateurs sit and wait for inspiration, the rest of us just get up and go to work.', author: 'Stephen King' },
  { text: 'Simplicity boils down to two steps: identify the essential and eliminate the rest.', author: 'Leo Babauta' },
  { text: 'Without hustle, talent will only carry you so far.', author: 'Gary Vaynerchuk' },
  { text: 'Do what is important now before what is urgent consumes your day.', author: 'Planner Principle' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'When we strive to become better than we are, everything around us becomes better too.', author: 'Paulo Coelho' },
  { text: 'The bad news is time flies. The good news is you are the pilot.', author: 'Michael Altshuler' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'A little planning today saves a lot of fixing tomorrow.', author: 'Productivity Wisdom' },
  { text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
  { text: 'You can do anything, but not everything.', author: 'David Allen' },
  { text: 'Done is better than perfect.', author: 'Sheryl Sandberg' },
  { text: 'Nothing is particularly hard if you divide it into small jobs.', author: 'Henry Ford' },
  { text: 'Success is steady progress toward worthy goals.', author: 'Earl Nightingale' },
  { text: 'Work hard in silence; let success be your noise.', author: 'Frank Ocean' },
  { text: 'One day or day one. You decide.', author: 'Paulo Coelho' },
  { text: 'Great acts are made up of small deeds.', author: 'Lao Tzu' },
  { text: 'Plan your work and work your plan.', author: 'Napoleon Hill' },
  { text: 'The chief thing is to keep the chief thing the chief thing.', author: 'Stephen Covey' },
  { text: 'Productivity is being able to do things that you were never able to do before.', author: 'Franz Kafka' },
  { text: 'If you want to make an easy job seem mighty hard, just keep putting off doing it.', author: 'Olin Miller' },
  { text: 'Do not be afraid to give up the good to go for the great.', author: 'John D. Rockefeller' },
  { text: 'Take care of the minutes and the hours will take care of themselves.', author: 'Lord Chesterfield' },
  { text: 'The beginning is the most important part of the work.', author: 'Plato' },
  { text: 'Success is simple. Do what is right, the right way, at the right time.', author: 'Arnold H. Glasow' },
  { text: 'You will never always be motivated, so you must learn to be disciplined.', author: 'Unknown' },
  { text: 'A productive day begins with a clear intention.', author: 'Daily Planning Reminder' },
  { text: 'Plan less perfectly, execute more consistently.', author: 'Daily Planning Reminder' }
]
